### PR TITLE
Add ssh-args flag.

### PR DESCRIPTION
**Pull request by ghost**
This pull request is incomplete. I am missing the logic for passing the arg to the runtime stdout.

If you want to provide it by editing my branch, great. If not, i'm sure I will figure it out.

### CODE REVIEW

**Comment by ghost** [comment]
When complete, this will resolve #114.

**Comment by ALSchwalm** [comment]
Thanks for working on this. Rather than adding a flag for ssh-key specifically, I'd rather generally solve this by adding a `-ssh-args` flag. This would allow a user to do any configuration they need to, including adding additional keying information like `-ssh-args "-i /path/to/key"`

**Comment by ghost** [comment]
> Thanks for working on this. Rather than adding a flag for ssh-key specifically, I'd rather generally solve this by adding a `-ssh-args` flag. This would allow a user to do any configuration they need to, including adding additional keying information like `-ssh-args "-i /path/to/key"`

Good idea.

**Comment by ghost** [comment]
I am going to close this PR and start from a clean branch.

**Comment by ALSchwalm** [comment]
Gotcha. I had to merge a change that added the ability to ssh in to an already running transient instance, and that caused some changes to the area you were working in. Let me know if you have any questions or run in to any issues

**Pull request closed without merging**
